apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      serviceAccountName: pubsub-app-sa
      containers:
      - name: flask-app
        image: us-docker.pkg.dev/iac-infra-proj-prod/gcr.io/flask-app:v2.1
        ports:
        - containerPort: 8080
        env:
        - name: DATABASE_HOST
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: DATABASE_HOST
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: DATABASE_USER
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: DATABASE_PASSWORD
        - name: DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: DATABASE_NAME
        - name: PUBSUB_PROJECT_ID
          valueFrom:
            secretKeyRef:
              name: pubsub-secrets
              key: PUBSUB_PROJECT_ID
        - name: PUBSUB_TOPIC_ID
          valueFrom:
            secretKeyRef:
              name: PUBSUB_TOPIC_ID
              key: topic_id
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  selector:
    app: flask-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP