---
name: Build and Push Image to Google Cloud Platform
on:
  push:
    branches: [ master ]
jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: flask-app
      PROJECT_ID: iac-infra-proj-prod
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: google-github-actions/setup-gcloud@v2
      with:
        service_account_key: ${{ secrets.GCP_CREDENTIALS }}
        project_id: ${{ env.PROJECT_ID }}
        export_default_credentials: true

    - name: Build Docker Image
      run: docker build -t flask-app:$GITHUB_SHA .

    - name: Automatic Tagging of Releases
      id: increment-git-tag
      run: |
        bash ./scripts/git_update.sh -v major

    - name: Configure Docker Client
      run: |-
        gcloud auth configure-docker --quiet
        gcloud auth configure-docker us-docker.pkg.dev --quiet

    - name: Push Docker Image to Container Registry (GCR)
      env:
        GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
      run: |-
        docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:$GITHUB_SHA
        docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:$GITHUB_SHA
        docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
        docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:$GITHUB_SHA

    - name: Push Docker Image to Artifact Registry
      env:
        GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
      run: |-
        docker tag $IMAGE_NAME:latest us-docker.pkg.dev/$PROJECT_ID/$IMAGE_NAME:latest
        docker tag $IMAGE_NAME:latest us-docker.pkg.dev/$PROJECT_ID/$IMAGE_NAME:$GITHUB_SHA
        docker push us-docker.pkg.dev/$PROJECT_ID/$IMAGE_NAME:latest
        docker push us-docker.pkg.dev/$PROJECT_ID/$IMAGE_NAME:$GITHUB_SHA