name: Build and Push Image to Google Cloud Platform
on:
  push:
    branches: [ master ]
jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: google-github-actions/setup-gcloud@v2
      with:
        service_account_key: ${{ secrets.GCP_CREDENTIALS }}
        project_id: iac-infra-proj-prod
        export_default_credentials: true

    - name: Build Docker Image
      run: docker build -t gcr.io/iac-infra-proj-prod/flask-app:v2.1 .

    - name: Configure Docker Client
      run: gcloud auth configure-docker us-docker.pkg.dev --quiet 
           

    - name: Push Docker Image to Container Registry (GCR)
      run: |-
        docker push gcr.io/iac-infra-proj-prod/flask-app:v2.1
