name: Build and Push Image to Google Cloud Platform
on:
  push:
    branches: [ master ]
jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    steps:
    # Checkout the repository
    - name: Checkout
      uses: actions/checkout@v2

    # Authenticate with Google Cloud
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    # Set up gcloud CLI
    - name: Set up Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: iac-infra-proj-prod

    # Build Docker image
    - name: Build Docker Image
      run: docker build -t us-docker.pkg.dev/iac-infra-proj-prod/gcr.io/flask-app:v2 .

    # Configure Docker to authenticate with Artifact Registry
    - name: Configure Docker Client
      run: gcloud auth configure-docker us-docker.pkg.dev --quiet

    # Push Docker image to Artifact Registry
    - name: Push Docker Image to Artifact Registry
      run: docker push us-docker.pkg.dev/iac-infra-proj-prod/gcr.io/flask-app:v2
